#!/usr/bin/env node

const { promisify } = require('util')
const { hideBin } = require('yargs/helpers')
const { resolve } = require('path')
const yargs = require('yargs/yargs')
const fs = require('fs')

const argv = yargs(hideBin(process.argv)).argv

const {
  Deck,
  Storage,
} = require(`../src`)

;(async () => {
  const configPath = resolve(argv.config || [ __dirname, 'config.json' ])

  let serviceConfigs = await promisify(fs.readFile)(configPath)
  serviceConfigs = JSON.parse(serviceConfigs.toString())

  const storage = new Storage.FS(argv.storage)
  const consumer = new Deck(storage, serviceConfigs)

  consumer.start()
})()
